/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { use, useRef } from 'react';
import { MeshReflectorMaterial, useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame, useThree } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    underscore: THREE.Mesh;
    l2: THREE.Mesh;
    l1: THREE.Mesh;
    e: THREE.Mesh;
    h: THREE.Mesh;
    o: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
  };
};

export function Model(props: React.ComponentProps<'group'>) {
  const [frame, setFrame] = React.useState(0);
  const { nodes, materials } = useGLTF('/portfolio_title.glb') as unknown as GLTFResult;
  const { viewport } = useThree();

  const timeRef = useRef<number>(0);
  const underscoreRef = useRef<THREE.Mesh>(null);

  React.useEffect(() => {
    const timeout = setTimeout(() => {
      setFrame((prev) => prev + 1);

      let count = 0;
      const interval = setInterval(() => {
        setFrame((prev) => prev + 1);
        count += 1;
        if (count >= 5) {
          clearInterval(interval);
        }
      }, 150);

      // Save interval ID so we can clear it if needed
      return () => clearInterval(interval);
    }, 1500);

    return () => clearTimeout(timeout);
  }, []);

  useFrame((_, delta) => {
    timeRef.current += delta;

    // Simple blink: 1s on, 1s off
    const blinkCycle = 2; // seconds
    const isOn = timeRef.current % blinkCycle < blinkCycle / 2;

    if (underscoreRef.current?.material) {
      (underscoreRef.current.material as THREE.MeshPhysicalMaterial).emissive = new THREE.Color(
        isOn ? '#2ac9fe' : '#000000',
      );
    }
  });

  return (
    <group {...props} dispose={null} scale={viewport.width / 14}>
      <mesh position={[0, -1.5, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <planeGeometry args={[100, 200]} />
        <MeshReflectorMaterial
          blur={[10, 10]}
          resolution={256}
          mixBlur={1}
          mixStrength={3}
          depthScale={1}
          minDepthThreshold={0.5}
          color="#dff2fe"
          metalness={0.1}
          roughness={0.5}
        />
      </mesh>
      <mesh
        ref={underscoreRef}
        castShadow
        receiveShadow
        geometry={nodes.underscore.geometry}
        material={materials['Material.001']}
        // Move from -3.958 to 3.958 proportionally as frame increases (assuming max frame is 6)
        position={[-3.958 + ((3.958 - -3.958) * Math.min(frame, 6)) / 6, -0.925, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={4.55}
      />

      {frame > 4 && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.l2.geometry}
          material={materials['Material.002']}
          position={[0.712, 0.22, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.55}
        ></mesh>
      )}
      {frame > 3 && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.l1.geometry}
          material={materials['Material.002']}
          position={[-0.893, 0.22, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.55}
        ></mesh>
      )}
      {frame > 2 && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.e.geometry}
          material={materials['Material.002']}
          position={[-2.491, 0.115, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.55}
        ></mesh>
      )}
      {frame > 1 && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.h.geometry}
          material={materials['Material.002']}
          position={[-4.154, 0.24, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.55}
        ></mesh>
      )}
      {frame > 5 && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.o.geometry}
          material={materials['Material.002']}
          position={[2.353, 0.111, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.55}
        ></mesh>
      )}
    </group>
  );
}

useGLTF.preload('/portfolio_title.glb');
